import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Kotlin version declaration and to what target
    kotlin("jvm") version "1.8.22"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    // snapshot repo containing rabbitmq kotlin client,
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots")
}

dependencies {
	// rabbitmq client (java)
    implementation("com.rabbitmq:amqp-client:5.20.0")
    // kotlin coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1-Beta")
    // rabbitmq client (kotlin)
    implementation("io.github.viartemev:rabbitmq-kotlin:0.7.0-SNAPSHOT")
    // redis client
    implementation("redis.clients:jedis:5.1.0")
    // redis client (kotlin)
    implementation("io.github.crackthecodeabhi:kreds:0.9.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    sourceCompatibility = JavaVersion.VERSION_17
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs += "-Xjsr305=strict"
        jvmTarget = "17"
    }
}

application {
    // Define the main class for the application.
    mainClass.set("psql_sketches.AppKt")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
