version: "3.3"

services:
  rabbit-mq:
    container_name: rabbit-mq
    build:
      context: .
      dockerfile: ./tests/Dockerfile-rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
  redis:
    container_name: redis
    image: redis:alpine
    ports:
     - "6379:6379"