version: '3'

# networks:
  # redis-cluster-network:
    # driver: bridge

services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  redis-node-1:
    image: redis:latest
    network_mode: host
    # networks:
      # - redis-cluster-network
    volumes:
      - ./7001:/redis
    command: redis-server /redis/redis.conf

  redis-node-2:
    image: redis:latest
    network_mode: host
    # networks:
      # - redis-cluster-network
    volumes:
      - ./7002:/redis
    command: redis-server /redis/redis.conf

  redis-node-3:
    image: redis:latest
    network_mode: host
    # networks:
      # - redis-cluster-network
    volumes:
      - ./7003:/redis
    command: redis-server /redis/redis.conf

  redis-node-4:
    image: redis:latest
    network_mode: host
    # networks:
      # - redis-cluster-network
    volumes:
      - ./7004:/redis
    command: redis-server /redis/redis.conf

  redis-node-5:
    image: redis:latest
    network_mode: host
    # networks:
      # - redis-cluster-network
    volumes:
      - ./7005:/redis
    command: redis-server /redis/redis.conf

  redis-node-6:
    image: redis:latest
    network_mode: host
    # networks:
      # - redis-cluster-network
    volumes:
      - ./7006:/redis
    command: redis-server /redis/redis.conf

  redis-cluster-init:
    image: redis:latest
    network_mode: host
    # networks:
      # - redis-cluster-network
    # command: redis-cli --cluster create redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 redis-node-4:7004 redis-node-5:7005 redis-node-6:7006 --cluster-replicas 1 --cluster-yes
    command: redis-cli --cluster create localhost:7001 localhost:7002 localhost:7003 localhost:7004 localhost:7005 localhost:7006 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
