version: "3.3"

services:
  db-tests:
    container_name: db-tests
    build:
      context: .
      dockerfile: ./tests/Dockerfile-db-test
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

  spring-service:
    build:
      context: .
      dockerfile: tests/Dockerfile-spring
    depends_on:
      - db-tests
      - rabbit-mq
      - redis
    command: ["scripts/wait-for-postgres.sh", "localhost"]
    environment:
      PORT: 8080
      DB_URL: "jdbc:postgresql://db-tests:5432/db?user=dbuser&password=changeit"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: tests/Dockerfile-nginx
    ports:
      - "8088:8088"

  # Just a machine running ubuntu, with 'dig' installed so that we can observe the docker compose environment.
  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: tests/Dockerfile-ubuntu
    tty: true

  rabbit-mq:
    container_name: rabbit-mq
    build:
      context: .
      dockerfile: ./tests/Dockerfile-rabbit
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"